version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directories:
      - /
      - /e2e/scripts/
    schedule:
      interval: daily
    groups:
      docker-images:
        group-by: dependency-name

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 0
      include:
        - "typisttech/*"
    groups:
      typisttech:
        patterns:
          - "typisttech/*"
