[tools]
"npm:portless" = "latest"
"npm:serve" = "latest"

[env]
GOEXPERIMENT = "jsonv2"
DOCKER = "docker"

[tasks.upgrade]
run = [
  'mise upgrade --bump --local',
  'go get -u -t -tags e2econtainer,e2escripts ./...',
  'go mod tidy',
]

[tasks.serve]
run = 'portless run -- go run ./cmd/serve'

[tasks.image]
depends = [{ task = "image:build" }]
run = '''
#!/usr/bin/env bash
set -e
app_port=($RANDOM + 65535 - 32767)

portless run --app-port "${app_port}" -- "${DOCKER}" run --rm -p "${app_port}:8080" wpsecadv-dev
'''

[tasks."image:build"]
run = '''
#!/usr/bin/env bash
set -e

mod=$(TZ=UTC git show -s --format=%cd --date=format:%Y-%m-%dT%H:%M:%SZ HEAD)
rev=$(git rev-parse --short HEAD)

if ! git diff --quiet --exit-code HEAD --; then
    mod=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    rev="${rev}-dirty"
fi

${DOCKER} build \
    --build-arg MOD_TIME=${mod} \
    --build-arg REVISION=${rev} \
    --tag wpsecadv-dev \
    .
'''

####################################
#
# Test
#
####################################

[tasks."test:unit"]
run = 'go test -count=1 -race -shuffle=on ./...'

[tasks."test:e2e:container"]
run = '''
#!/usr/bin/env bash
set -e

echo "==> Running e2e tests within containers. This could take a while..."
go test -tags=e2econtainer -count=1 -shuffle=on ./e2e/container/... $@
'''

[tasks."test:e2e:local"]
run = '''
#!/usr/bin/env bash
set -e

export TESTSCRIPT_COMPOSER_CACHE_DIR="$(composer global config cache-dir --absolute --quiet)"
export TESTSCRIPT_COMPOSER_CAFILE="$HOME/.portless/ca.pem"

name="wpsecadv-e2e-local"

echo "==> Starting server in the background..."
portless run --name "${name}" -- go run ./cmd/serve > /dev/null 2>&1 &
pid=$!

cleanup () {
    echo "==> Cleaning up..."
    echo "Terminating the server (pid: '"${pid}"')..."
    kill -9 "${pid}" || true
}
trap 'cleanup' EXIT

export WPSECADV_SERVER_URL=$(portless get "${name}")

echo "==> Waiting for server '"${WPSECADV_SERVER_URL}/packages.json"' ready..."
curl --silent --out-null -X GET --fail --retry 10 --retry-all-errors --retry-connrefused --retry-delay 1 "${WPSECADV_SERVER_URL}/packages.json"

echo "==> Running e2e tests with system composer. This could take a while..."
go test -tags=e2escripts -count=1 -shuffle=on ./e2e/scripts/... $@
'''

[tasks."test:e2e:prod"]
env.WPSECADV_SERVER_URL = { value = "{{ get_env(name='WPSECADV_SERVER_URL', default='https://repo-wpsecadv.typist.tech') }}" }
run = '''
#!/usr/bin/env bash
set -e

echo "==> Waiting for server '"${WPSECADV_SERVER_URL}/packages.json"' ready..."
curl --silent --out-null -X GET --fail --retry 10 --retry-all-errors --retry-connrefused --retry-delay 1 "${WPSECADV_SERVER_URL}/packages.json"

echo "==> Running e2e tests with system composer. This could take a while..."
go test -tags=e2escripts -count=1 -shuffle=on ./e2e/scripts/... $@
'''

####################################
#
# Lint
#
####################################

[tasks.lint]
run = [
  'go mod tidy -diff',
  'golangci-lint run',
]

[tasks.fmt]
run = 'golangci-lint fmt'

####################################
#
# Code Generation & Cleanup
#
####################################

[tasks.gen]
env.WORDFENCE_INTELLIGENCE_API_KEY = { required = true, redact = true }
run = 'go generate ./...'

[tasks."gen:data:fixture"]
env.FEED_FIXTURE = { required = true }
run = '''
#!/usr/bin/env bash
set -e

export WORDFENCE_INTELLIGENCE_API_KEY="dummy"
export FEED_FIXTURE_DIR=$(dirname "${FEED_FIXTURE}")
export FEED_FIXTURE_BASENAME=$(basename "${FEED_FIXTURE}")

name="wpsecadv-gen-data-fixture"

echo "==> Starting server in the background..."
portless run --name "${name}" -- serve "${FEED_FIXTURE_DIR}" > /dev/null 2>&1 &
pid=$!

cleanup () {
    echo "==> Cleaning up..."
    echo "Terminating the server (pid: '"${pid}"')..."
    kill -9 "${pid}" || true
}
trap 'cleanup' EXIT

export WORDFENCE_FEED_URL="$(portless get "${name}")/${FEED_FIXTURE_BASENAME}"

echo "==> Waiting for server '"${WORDFENCE_FEED_URL}"' ready..."
curl --silent --out-null -X GET --fail --retry 10 --retry-all-errors --retry-connrefused --retry-delay 1 "${WORDFENCE_FEED_URL}"

echo "==> Generating data from fixture..."
go generate ./internal/data $@
'''

[tasks."gen:packagist"]
run = 'go generate ./internal/packagist'

[tasks.clean]
depends = ["clean:*"]

[tasks."clean:data"]
run = [
  'rm -rf internal/data/assets',
  'rm -rf internal/data/assets_gen.go',
  'rm -rf internal/data/assets_gen_test.go',
]

[tasks."clean:packagist"]
run = 'rm -rf internal/packagist/core_gen.go'

[tasks."clean:test"]
run = 'rm -rf _artifacts'
