// Code generated by go generate in packagist/doc.go:3; DO NOT EDIT.

package packagist

// IsCoreImplementation reports whether the given package
// is one of the [CoreImplementations] packages.
func IsCoreImplementation(vendor, project string) bool {
	switch vendor {
	case "composer-wordpress":
		switch project {
		case "full":
			return true
		}
	case "johnpbloch":
		switch project {
		case "wordpress-core":
			return true
		}
	case "leocolomb":
		switch project {
		case "wordpress":
			return true
		}
	case "medreleaf":
		switch project {
		case "wordpress":
			return true
		}
	case "mythic":
		switch project {
		case "wordpress-starter-project":
			return true
		}
	case "onepress":
		switch project {
		case "wordpress-no-content":
			return true
		}
	case "pantheon-systems":
		switch project {
		case "wordpress-composer":
			return true
		}
	case "plott":
		switch project {
		case "plottcore-wordpress-no-content":
			return true
		}
	case "roots":
		switch project {
		case "wordpress-full":
			return true
		case "wordpress-no-content":
			return true
		}
	}

	return false
}

// CoreImplementations returns a list of WordPress core implementation package
// names in the format of `vendor/project`.
//
// This is based on the list of packages on packagist.org that either:
//   - provides the [wordpress/core-implementation] virtual package
//   - has the type [wordpress-core]
//
// [wordpress/core-implementation]: https://packagist.org/providers/wordpress/core-implementation
// [wordpress-core]: https://packagist.org/providers/wordpress/core-implementation?type=wordpress-core
func CoreImplementations() []string {
	return []string{
		"composer-wordpress/full",
		"johnpbloch/wordpress-core",
		"leocolomb/wordpress",
		"medreleaf/wordpress",
		"mythic/wordpress-starter-project",
		"onepress/wordpress-no-content",
		"pantheon-systems/wordpress-composer",
		"plott/plottcore-wordpress-no-content",
		"roots/wordpress-full",
		"roots/wordpress-no-content",
	}
}
