name: Audit

on:
  workflow_dispatch:
  schedule:
    - cron: '7 3 * * 1' # Weekly on Monday
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  govulncheck:
    uses: typisttech/.github/.github/workflows/audit-go.yml@04cdd7b57745cee6082fa921de418e82209ef77a # v4.0.1
    with:
      go-experiment: jsonv2
