name: Audit

on:
  workflow_dispatch:
  schedule:
    - cron: '7 3 * * 1' # Weekly on Monday
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  govulncheck:
    uses: typisttech/.github/.github/workflows/audit-go.yml@872d5345c254c6f8d65f318e5bffa74d7d0192e2 # v5.0.1
    with:
      go-experiment: jsonv2
