name: Dependabot Auto-merge

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    uses: typisttech/.github/.github/workflows/dependabot-auto-merge.yml@68b2ff84a9d7b58ee3943e697f76cd9a3a51f8cc
    with:
      minor: true
      patch: true
