name: Dependabot Auto-merge

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    uses: typisttech/.github/.github/workflows/dependabot-auto-merge.yml@95a3cb060227892cf7956e2564a8c89d578620da # v5.1.0
    with:
      minor: true
      patch: true
