name: Dependabot Auto-merge

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    uses: typisttech/.github/.github/workflows/dependabot-auto-merge.yml@86c07906e5ad8ccd4bab27975f7f67e348498f82 # v5.4.0
    with:
      minor: true
      patch: true
