name: Deploy

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Container image tag to deploy'
        required: true
        default: 'latest'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions: {}

jobs:
  fly:
    runs-on: ubuntu-24.04
    environment: production-fly
    steps:
      - uses: imjasonh/setup-crane@6da1ae018866400525525ce74ff892880c099987 # v0.5
      - run: echo digest="$(crane digest "${IMAGE}")" >> "$GITHUB_OUTPUT"
        id: crane
        env:
          IMAGE: ghcr.io/${{ github.repository }}:${{ github.event.inputs.tag }}

      - uses: sigstore/cosign-installer@ba7bc0a3fef59531c69a25acd34668d6d3fe6f22 # v4.1.0
      - run: |
          cosign verify \
            --certificate-oidc-issuer https://token.actions.githubusercontent.com \
            --certificate-identity-regexp "${CERTIFICATE_IDENTITY_REGEXP}" \
            --certificate-github-workflow-repository "${REPO}" \
            "${IMAGE}"
        env:
          CERTIFICATE_IDENTITY_REGEXP: '^https://github.com/${{ github.repository }}/.github/workflows/publish.yml.*$'
          REPO: ${{ github.repository }}
          IMAGE: ghcr.io/${{ github.repository }}@${{ steps.crane.outputs.digest }}

      - uses: superfly/flyctl-actions/setup-flyctl@fc53c09e1bc3be6f54706524e3b82c4f462f77be # 1.5
      - run: flyctl deploy --image "${IMAGE}"
        env:
          IMAGE: ghcr.io/${{ github.repository }}@${{ steps.crane.outputs.digest }}
          FLY_APP: ${{ vars.FLY_APP }}
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
