name: Lint

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  GOEXPERIMENT: jsonv2

jobs:
  actions:
    uses: typisttech/.github/.github/workflows/lint-actions.yml@154a3cb184890192d50962968de68a071b45870b # v4.0.0

  go:
    uses: typisttech/.github/.github/workflows/lint-go.yml@154a3cb184890192d50962968de68a071b45870b # v4.0.0
    with:
      go-experiment: jsonv2
      golangci-lint-version: v2.11 # Must be kept in sync with mise.toml

  fly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          sparse-checkout: fly.toml

      - uses: superfly/flyctl-actions/setup-flyctl@fc53c09e1bc3be6f54706524e3b82c4f462f77be # 1.5
      - run: flyctl config validate --strict
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_ORG_READONLY }}

  wait-for-all-lint:
    needs:
      - actions
      - go
      - fly
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
