name: Lint

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  GOEXPERIMENT: jsonv2

jobs:
  actions:
    uses: typisttech/.github/.github/workflows/lint-actions.yml@8c3b859e35165a6e81a660713be195ec61d2ca1d # v5.2.1

  go:
    uses: typisttech/.github/.github/workflows/lint-go.yml@3b989be3639ac84acd7770ad0795ffbfc6193b2b # v5.2.2
    with:
      go-experiment: jsonv2
      golangci-lint: true
      golangci-lint-version: v2.12 # Must be kept in sync with mise.toml

  fly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          sparse-checkout: fly.toml

      - uses: superfly/flyctl-actions/setup-flyctl@ed8efb33836e8b2096c7fd3ba1c8afe303ebbff1 # 1.6
      - run: flyctl config validate --strict
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_ORG_READONLY }}

  wait-for-all-lint:
    needs:
      - actions
      - go
      - fly
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
