name: Publish Container Image

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions: {}

jobs:
  image:
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read
      id-token: write
      packages: write
    with:
      output: image
      push: true
      platforms: linux/amd64,linux/arm64
      meta-images: ghcr.io/${{ github.repository }}
      meta-tags: |
        type=raw,value=latest,enable={{is_default_branch}}
        type=raw,value={{commit_date 'YYYYMMDDHHmmss'}}
        type=sha
      set-meta-annotations: true
      set-meta-labels: true
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

  dispatch:
    if: github.ref_name == 'main'
    needs:
      - image
    permissions:
      actions: write
    runs-on: ubuntu-24.04
    steps:
      - name: Dispatch Deploy Workflow
        run: |
          gh workflow run deploy.yml \
            --repo "${REPO}" \
            --ref "${REF}"
        env:
          REPO: ${{ github.repository }}
          REF: ${{ github.ref_name }}
          GH_TOKEN: ${{ github.token }}
