name: Test (e2e)

on:
  workflow_call:
    inputs: &inputs
      url:
        required: true
        type: string
  workflow_dispatch:
    inputs: *inputs

permissions:
  contents: read

env:
  GOEXPERIMENT: jsonv2

jobs:
  test:
    name: ${{ inputs.url || 'Local' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: 'go.mod'
      - uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      - run: go test -tags=e2econtainer -count=1 -shuffle=on ./e2e/container/...
        env:
          WPSECADV_SERVER_URL: ${{ inputs.url }}
