name: Update Data

on:
  workflow_dispatch:
  schedule:
    - cron: '34 5,17 * * *' # Twice a day

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  GOEXPERIMENT: jsonv2

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: 'go.mod'

      - run: go generate ./...
        env:
          WORDFENCE_INTELLIGENCE_API_KEY: ${{ secrets.WORDFENCE_INTELLIGENCE_API_KEY }}

      - uses: typisttech/create-auto-merged-pull-request-action@42c8119c5e4397506847dc4d27168e98ce69dfc7 # v0.1.0
        with:
          app-id: ${{ vars.TASTENDRUCK_APP_ID }}
          private-key: ${{ secrets.TASTENDRUCK_PRIVATE_KEY }}
          branch: "tastendruck/github_actions/go-generate/${{ github.ref_name }}"
          title: ":robot: `go generate ./...`"
          labels: go-generate
          add-paths: |
            **/*_gen.go
            **/*_gen_test.go
            **/*_gen.json
