name: Update Data

on:
  workflow_dispatch:
  schedule:
    - cron: '34 5,17 * * *' # Twice a day

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  GOEXPERIMENT: jsonv2

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: 'go.mod'

      - run: go generate ./...
        env:
          WORDFENCE_INTELLIGENCE_API_KEY: ${{ secrets.WORDFENCE_INTELLIGENCE_API_KEY }}

      - uses: typisttech/create-auto-merged-pull-request-action@22b38db196d8c7945e1580e3b10a92651fb73b07 # v0.2.4
        with:
          client-id: ${{ vars.TASTENDRUCK_CLIENT_ID }}
          private-key: ${{ secrets.TASTENDRUCK_PRIVATE_KEY }}
          branch: "tastendruck/github_actions/go-generate/${{ github.ref_name }}"
          title: ":robot: `go generate ./...`"
          labels: go-generate
          add-paths: |
            **/*_gen.go
            **/*_gen_test.go
            **/*_gen.json
